### ISSUE TITLE
Check function (1,2,3,4) used

### ISSUE THREAD

**Issue by WendellRocha** [v-zhuravlev/libzbxmodbus#16]
Hello, I am trying to get data from a Schneider PM1200 through zabbix_get and when I execute the command I get the message: `check function (1,2,3,4) used`.

I'm trying like this: `zabbix_get -s localhost -p 10050 -k modbus_read [{$ MODBUS_PORT}, 3927,4, f, 1,0]`

`{$MODBUS_PORT} = / dev / ttyUSB0 9600 E 8 1`

Sorry for my English, I used Google Translate.

**Comment by v-zhuravlev** [comment]
Hi, please check you parameters inside [] 
https://github.com/v-zhuravlev/libzbxmodbus/blob/master/README.md

4th parameter should be either: 1,2,3,4: where:
1 - for READ COILS
2 - for READ DISCRETE INPUT STATUS
3 - for READ HOLDING REGISTERS
4 - for READ INPUT REGISTERS
but you have `f`.
