### ISSUE TITLE
Using values in calculations

### ISSUE THREAD

**Issue by swapper82** [v-zhuravlev/libzbxmodbus#24]
Hi 
Is it possible to use the module when doing calculated values?
i get errors when trying:
(last("Diris A40 - pre UPS:modbus_read_registers[192.168.1.1,5,51293,3,i,1,1]"))/(last("Diris A40 - post UPS:modbus_read_registers[192.168.1.1,4,51293,3,i,1,1]"))

**Comment by v-zhuravlev** [comment]
yes, you can use any items in calculations, no matter how they are collected. please check zabbix docs.
