### ISSUE TITLE
Unsupported item key.

### ISSUE THREAD

**Issue by mxj333** [v-zhuravlev/libzbxmodbus#26]
Hello:

I created a items :
```
Name: A V Sensor
Type: Simple check
Key: modbus_read[192.168.0.174,2,57,4,f]
Type of information: Numeric(float)
Units: C

```
After saving, the state of the items is
```
	Not supported
```
info:

```
Unsupported item key.
```

Any idea on how to resolve this problem? 

thank you！

**Comment by mxj333** [comment]
It was successful when it was just configured, and it appeared in a few days：
```
Unsupported item key.
```

**Comment by v-zhuravlev** [comment]
Hi, could please provide more information? Can you successfully continuously poll you device using `modpoll` utility?

**Comment by i-ky** [comment]
Module hasn't been loaded by Zabbix server/proxy/agent I guess. It is worth checking configuration file.
