### ISSUE TITLE
Возвращаемое значение

### ISSUE THREAD

**Issue by anekrasov** [v-zhuravlev/libzbxmodbus#4]
Если  modbus_function = 3, datatype = i и возврощаемое значение <0, в Zabbix поподает 65536 - возврощаемое значение.
Например:
modpoll 3.4 - FieldTalk(tm) Modbus(R) Master Simulator
Copyright (c) 2002-2013 proconX Pty Ltd
Visit http://www.modbusdriver.com for Modbus libraries and tools.
Protocol configuration: Modbus RTU
Slave configuration...: address = 32, start reference = 295 (PDU), count = 1
Communication.........: /dev/ttyUSB0, 9600, 8, 1, none, t/o 1.00 s, poll rate 1000 ms
Data type.............: 16-bit register, output (holding) register table
-- Polling slave...
[295]: -337
zabbix_get -s 10.5.35.121 -k 'modbus_read_registers[/dev/ttyUSB0,32,295,3,i]'
65199

**Comment by v-zhuravlev** [comment]
Сейчас INTEGER это как и в Zabbix - целое положительное число. Чтобы целое число могло быть и с запятой, я добавил новый тип данных,MODBUS_SIGNED_INTEGER.
Можно взять потестить в этом коммите: [https://github.com/v-zhuravlev/libzbxmodbus/commit/bd4dc2965f98db6d0fe7c7b377cbdca7b5f6c1ef](url)

При этом нужно будет: 
'modbus_read_registers[/dev/ttyUSB0,32,295,3,i]'
поменять на 
'modbus_read_registers[/dev/ttyUSB0,32,295,3,s]'

и тип данных(type of information) в Zabbix на Numeric(float).

отпишитесь о результате тестирования
