### ISSUE TITLE
Zabbix 3.0 support

### ISSUE THREAD

**Issue by anisimovev** [v-zhuravlev/libzbxmodbus#5]
У меня перестал работать модуль после обновления с 2.4 на 3.0
Планируется ли поддержка версии 3.0?

**Comment by v-zhuravlev** [comment]
Да, постараюсь разобраться в чем дело.

**Comment by v-zhuravlev** [comment]
Try this out:

https://github.com/v-zhuravlev/libzbxmodbus/blob/6f2502dfb21e4b49cd1d0db4d79767a26558e589/libzbxmodbus-0.3.tar.gz

**Comment by anisimovev** [comment]
Работает, спасибо!
