### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by bobbyps23** [v-zhuravlev/libzbxmodbus#61]
hi. I'm still newb at zabbix. So, I want to ask you, where I should write or entry the configuration like "LoadModulePath" is?Am I need to put or install "zabbix_agentd.conf" and zabbix_agentd.exe to wrte the configuration and execute the module? Would you help me please.

**Comment by i-ky** [comment]
> where I should write or entry the configuration like "LoadModulePath"

Into Zabbix [server](https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_server), [proxy](https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_proxy) or [agent](https://www.zabbix.com/documentation/current/manual/appendix/config/zabbix_agentd) configuration file. Unfortunately, loadable modules (including this one) are only supported on UNIX, see [this feature request](https://support.zabbix.com/browse/ZBXNEXT-2201).
