### ISSUE TITLE
2 protocol

### ISSUE THREAD

**Issue by bobbyps23** [v-zhuravlev/libzbxmodbus#63]
Hai, sorry for another question, I've success on installing libmodbuszbx. Here's the problem, can it installed along with SNMP?if it can, then should I change the prefix to /var/lib/module?because I need to monitoring this 2 protocol. Thanks

**Comment by i-ky** [comment]
I don't know what you actually mean by "installing SNMP". Zabbix agent protocol and SNMP are two completely independent protocols and their configurations don't affect each other.

**Comment by bobbyps23** [comment]
I'm sorry, I forgot that SNMP is already installed from the start. But it LoadModulePath it's in the zabbix_server.conf too, so I can't put LoadModulePath for libzbxmodbus there, it will make zabbix server stopped because it will search for module.so for modbus in SNMP's module Path directory. So what should I do so I can read SNMP and Modbus in the same time without causing error in zabbix server?

**Comment by i-ky** [comment]
Zabbix server supports SNMP out of the box, you don't need any modules for that...

In case you need to use two or more loadable modules, they all have to be located in the same directory (`LoadModulePath`). Latest versions of Zabbix also support absolute path in `LoadModule` (see [the feature request](https://support.zabbix.com/browse/ZBXNEXT-5179) for more details).

**Comment by bobbyps23** [comment]
So, if I've already put the module for modbus in the same directory(LoadModulePath) as the SNMP's directory, do I also need to write libmodbus.so in LoadModule too or not? I'm so sorry for asking too many, because I'm still vague about it.

**Comment by i-ky** [comment]
Yes, one `LoadModule` for every module you want to use.

**Comment by bobbyps23** [comment]
Okay then. Great thanks a lot.

**Comment by v-zhuravlev** [comment]
@i-ky , thanks for keeping this repo responsive :)
