### ISSUE TITLE
Cannot read so much data at once

### ISSUE THREAD

**Issue by turkertopal** [v-zhuravlev/libzbxmodbus#65]
Hi,

I am trying to read two Uint64 registers from a device, one at register 30513 and second is at 30775. Because they are very far from each others it returns "Cannot read so much data at once". I see in the code that you wanted to update this part. Any chance you are going to look at this in the nearest future?
This is a very important feature for my case - as I am connecting to a very old device, which has unstable connection, refuses connection every other time. So i get reasonable history on one metric and almost no data on the other.

**Comment by i-ky** [comment]
Hi!

Indeed, it shouldn't be too hard to do, we were simply waiting for someone like you who actually needs it. You may also benefit from #64, so don't be shy and add a comment there as well.
