### ISSUE TITLE
multiple serial port possibility

### ISSUE THREAD

**Issue by javadgo** [v-zhuravlev/libzbxmodbus#68]
Hi
Thanks a bunch for this great repo, Vitaly you are the best.
I have a question and I would be very grateful if anyone can give me an answer.
As it's well described in  README file, all serial port configuration is in items key definition in zabbix UI.
My PC have two serial port, can I connect two different modbus line to each serial ports like below structure?

![Untitled-1](https://user-images.githubusercontent.com/22274795/79426821-f519e580-7fd8-11ea-919b-61b5c7e05f02.png)

Main question is, is it possible to for libzbxmodbus to handle multiple serial port at the same time?

**Comment by i-ky** [comment]
I don't see anything related among [limitations](https://github.com/v-zhuravlev/libzbxmodbus#7-known-issues-and-limitations), so it should be possible. I think you should try!

**Comment by i-ky** [comment]
I am going to assume that everything went fine and close the issue. @javadgo, feel free to reopen or create new issues if you have more questions or experience any problems.
