### ISSUE TITLE
libzbxmodbus

### ISSUE THREAD

**Issue by behzad831371** [v-zhuravlev/libzbxmodbus#70]
Hi,
I tested my connection with modpoll and received the data. When I try to read the modbus in zabbix, it seems that the connection is established and no unsupported item, but the data is different than what it should be and is always 0.
Thanks.

![item](https://user-images.githubusercontent.com/60315927/82188343-fce3e700-9902-11ea-9820-c008b98f073d.png)
![modpoll](https://user-images.githubusercontent.com/60315927/82188354-01100480-9903-11ea-890a-6ea294d70d78.png)
![zabbix](https://user-images.githubusercontent.com/60315927/82188368-040af500-9903-11ea-97d0-3a17364b797e.png)

**Comment by v-zhuravlev** [comment]
Check things like endianess and so on and whether they match in modpoll and zabbix modbus. Those things can be set by using optional params in zabbix item key. To speed up troubleshooting - I recommend to test modbus using `zabbix_get` or `zabbix_agentd -t` cli commands.

**Comment by behzad831371** [comment]
Thank you for your answer
But I am a very beginner can I get more help from you?
I have been involved for some time, I tried but unfortunately it did not work
