### ISSUE TITLE
Zabbix version 5.0

### ISSUE THREAD

**Issue by OG0505** [v-zhuravlev/libzbxmodbus#71]
i am trying to do the following command:
./configure --prefix=/etc/zabbix --enable-zabbix-5.0

And i am getting the following error code:
Please specify the version of Zabbix module will be used with: by providing either
--enable-zabbix-2 or --enable-zabbix-3 or --enable-zabbix-3.2 key but no more than one.

What am i doing wrong?
My zabbix version is 5.0.1

I tried the following commands also and i am getting the same error:
./configure --prefix=/etc/zabbix --enable-zabbix-5
./configure --prefix=/etc/zabbix --enable-zabbix-5.0.1

![image](https://user-images.githubusercontent.com/67459190/85837461-522fd580-b798-11ea-922e-fe18d536c50c.png)

**Comment by i-ky** [comment]
> What am i doing wrong?

Nothing. This part hasn't been updated since Zabbix 3.2 and no surprise that nowadays it is a bit confusing.

Luckily, Zabbix headers didn't change much either (if at all), so I guess you will be fine if you use `--enable-zabbix-3.2` with Zabbix 5.0.

**Comment by OG0505** [comment]
Thankyou it worked! with the 3.2 key
