### ISSUE TITLE
Check SlaveID parameter

### ISSUE THREAD

**Issue by OG0505** [v-zhuravlev/libzbxmodbus#72]
Hi,

I configured the modbus items on the Raspberry Pi just like the manual says but i am getting a error on the modbus request item.
- Check slaveid parameter.

I dont know what to do know. 
Did i forget something?
How do i know if the modbus is working right know?

![image](https://user-images.githubusercontent.com/67459190/86374464-e44a4900-bc84-11ea-9da8-d2f6de944c51.png)
![image](https://user-images.githubusercontent.com/67459190/86374654-1a87c880-bc85-11ea-8048-e742fe530662.png)
![image](https://user-images.githubusercontent.com/67459190/86374726-2e332f00-bc85-11ea-8cd6-4417d4af8c87.png)
![image](https://user-images.githubusercontent.com/67459190/86374833-486d0d00-bc85-11ea-9de5-80afebf2f55f.png)
![image](https://user-images.githubusercontent.com/67459190/86374919-620e5480-bc85-11ea-9126-a1d70eb6c1f1.png)

**Comment by i-ky** [comment]
Hi!

It looks like you are using [item testing](https://www.zabbix.com/documentation/current/manual/config/items/item#testing) functionality. Unfortunately, I don't have a hands on experience with this feature. And unfortunately, Zabbix documentation does not say anything about _Macros_. But I suppose Zabbix has detected that item key you want to test depends on macros and you are supposed to provide their values in input boxes next to &rArr;. Alternatively, for the sake of testing, you can replace macros with their values in the item key itself.

**Comment by i-ky** [comment]
Almost a year without response. I am going to close the issue. @OG0505, feel free to reopen if the issue still persists.
