### ISSUE TITLE
Set timeout for requests

### ISSUE THREAD

**Issue by phmazzoni** [v-zhuravlev/libzbxmodbus#8]
Hello,

First, thank you so much for the module, it is really great! Congrats!
One question:
Is it possible to set the timeout for the requests?

Thanks in advance,
Pedro Mazzoni

**Comment by v-zhuravlev** [comment]
Thanks. What kind of timeout are you talking about?

**Comment by v-zhuravlev** [comment]
Also please check what version of libmodbus you are using - 3.0.6 (latest stable) has problems with timeouts. I recommend to use 3.1.2

**Comment by v-zhuravlev** [comment]
Timeouts configuration implemented in v0.5 (also see issue #11)
