### ISSUE TITLE
unsupported module "libzbxmodbus.so" version: 1

### ISSUE THREAD

**Issue by liuhuan94** [v-zhuravlev/libzbxmodbus#81]
Hello developer, I installed and deployed libzbxmodbus in Zabbix5.4, but it is not supported, please help me, thank you!
![image](https://user-images.githubusercontent.com/86298272/142165621-d5e17b0e-3443-435f-8902-13adbb13b6bc.png)

**Comment by i-ky** [comment]
@liuhuan94, did you compile libzbxmodbus yourself? If yes, what was your `./configure` command? For Zabbix 3.2 and later something like this should work:
```
./configure --enable-zabbix-3.2 ...
```

**Comment by liuhuan94** [comment]
> @liuhuan94, did you compile libzbxmodbus yourself? If yes, what was your `./configure` command? For Zabbix 3.2 and later something like this should work:
> 
> ```
> ./configure --enable-zabbix-3.2 ...
> ```
Of course, zabbix log still shows failure after compilation
![image](https://user-images.githubusercontent.com/86298272/142167434-f42939b7-ccb3-4221-ac4d-4b1167385309.png)

**Comment by liuhuan94** [comment]
![image](https://user-images.githubusercontent.com/86298272/142167794-e4d47272-49cc-495c-9aa7-fc197954ad1f.png)
![image](https://user-images.githubusercontent.com/86298272/142167872-4869b9bf-dd9b-46ef-9d55-bc2cc808df50.png)

**Comment by liuhuan94** [comment]
![image](https://user-images.githubusercontent.com/86298272/142168139-431d78ed-9120-44b1-9f41-3828c4e01ed4.png)

**Comment by i-ky** [comment]
Just to double check. Did you run `make` after `./configure --enable-zabbix-3.2`?

**Comment by liuhuan94** [comment]
> Just to double check. Did you run `make` after `./configure --enable-zabbix-3.2`?

Ah yes，I installed it through Git. Now I uninstall the previous installation and download the installation package again for compilation. No error has been reported so far.Thank you！

**Comment by i-ky** [comment]
You are welcome!
