### ISSUE TITLE
modbus.read timeout

### ISSUE THREAD

**Issue by liuhuan94** [v-zhuravlev/libzbxmodbus#82]
Hi developer, I don't understand why modbus.read shows timeout when testing port pass.I used nc -zv test port connect show sucess

![image](https://user-images.githubusercontent.com/86298272/142598897-29e52014-fe06-445e-ad00-cf88998be9b9.png)
![image](https://user-images.githubusercontent.com/86298272/142598944-eb2cc840-707b-4f85-942c-459cd47aa5a8.png)

**Comment by i-ky** [comment]
@liuhuan94, this error message comes from libmodbus, which is used by this module to perform actual communications. If I were you, I would try to capture traffic while doing `modbus.read` (using `tcpdump` & Co.), this may shed some light on the issue.

**Comment by liuhuan94** [comment]
I looked at it and it worked。
![image](https://user-images.githubusercontent.com/86298272/142604874-ff72eae4-6308-4903-94e2-a1b323254f00.png)

**Comment by i-ky** [comment]
@liuhuan94, is the issue resolved?

**Comment by liuhuan94** [comment]
> @liuhuan94, is the issue resolved?

used the modbus_read_registers [TCP: / / 10.148.20.24:501,1,2,3, s, 0] can get data,But if you poll all the data in the register, the connection is refused

![image](https://user-images.githubusercontent.com/86298272/142796372-f5f37bf4-744d-4950-b057-5919c8de8d74.png)

**Comment by liuhuan94** [comment]
Sorry，The port number above is wrong. It should be this one
![image](https://user-images.githubusercontent.com/86298272/142797284-d613b135-d7dc-42cc-9ef6-c10664ea511a.png)

**Comment by i-ky** [comment]
@liuhuan94, like I said [above](https://github.com/v-zhuravlev/libzbxmodbus/issues/82#issuecomment-973911372), I have no way of helping you unless you capture the traffic.

**Comment by liuhuan94** [comment]
> @liuhuan94，就像我[上面](https://github.com/v-zhuravlev/libzbxmodbus/issues/82#issuecomment-973911372)说的，除非你抓住流量，否则我无法帮助你。

display success

![image](https://user-images.githubusercontent.com/86298272/142842316-7458133e-cc1e-41a1-90ef-7a6d48a0a4ea.png)

**Comment by i-ky** [comment]
@liuhuan94, have you tried testing your item key with `zabbix_get` or `zabbix_agentd -t`?

**Comment by liuhuan94** [comment]
> @liuhuan94, have you tried testing your item key with `zabbix_get` or `zabbix_agentd -t`?

Zabbix_get requires the installation of Zabbix Agent in the data acquisition terminal, but my device is an IOT temperature and humidity collector, so I cannot use ZabbiX_GET for testing

**Comment by i-ky** [comment]
@liuhuan94, you can install `zabbix_get` and Zabbix agent into the same box where your Zabbix server is. And query your IOT device using agent just like you do with Zabbix server, but using agent will help isolate the issue, hopefully.

**Comment by liuhuan94** [comment]
>

**Comment by liuhuan94** [comment]
> @liuhuan94, you can install `zabbix_get` and Zabbix agent into the same box where your Zabbix server is. And query your IOT device using agent just like you do with Zabbix server, but using agent will help isolate the issue, hopefully.

The problem has been solved, I found the problem, the parameter setting and register reading position is wrong, causing the connection timeout.Thank you for guiding me through mistakes.
